import { Droplets } from "lucide-react";
import { useTranslation } from "react-i18next";
import { DoorPageShell, DoorGrid } from "./DoorCard";
import type { DoorProduct } from "./DoorCard";

const products: DoorProduct[] = [
  // ── Turkish Made ────────────────────────────────────────────────────────────
  {
    id: "pvc-tr-1",
    name: "PVC Door 1",
    tag: "Turkish",
    variants: [{ image: "https://lh3.googleusercontent.com/d/106nO6531RjoG_E7dRPXPdDA5wOoXUCge", color: "" }],
    description: "",
    specs: [],
  },
  {
    id: "pvc-tr-2",
    name: "PVC Door 2",
    tag: "Turkish",
    variants: [{ image: "https://lh3.googleusercontent.com/d/17h3a7ErHmwtMAYQmZTCPQ9qDh2Q-7v85", color: "" }],
    description: "",
    specs: [],
  },
  {
    id: "pvc-tr-3",
    name: "PVC Door 3",
    tag: "Turkish",
    variants: [{ image: "https://lh3.googleusercontent.com/d/18e5pj2qRxX2LhHiBJ4l6wslOLAV6NWPB", color: "" }],
    description: "",
    specs: [],
  },
  {
    id: "pvc-tr-4",
    name: "PVC Door 4",
    tag: "Turkish",
    variants: [{ image: "https://lh3.googleusercontent.com/d/1AY4TUbalYKKETdHkETN64xAqkM_zLRtb", color: "" }],
    description: "",
    specs: [],
  },
  {
    id: "pvc-tr-5",
    name: "PVC Door 5",
    tag: "Turkish",
    variants: [{ image: "https://lh3.googleusercontent.com/d/1CJPoZIrKDPFEl7tlGRHo2DtpNAiL3Ejt", color: "" }],
    description: "",
    specs: [],
  },
  {
    id: "pvc-tr-6",
    name: "PVC Door 6",
    tag: "Turkish",
    variants: [{ image: "https://lh3.googleusercontent.com/d/1F4VkUmA2TQ9eiikth0HDtitLwfdkqclJ", color: "" }],
    description: "",
    specs: [],
  },
  {
    id: "pvc-tr-7",
    name: "PVC Door 7",
    tag: "Turkish",
    variants: [{ image: "https://lh3.googleusercontent.com/d/1GR40zpiL2alz2sDpkQaVvyq2uA2ErgiO", color: "" }],
    description: "",
    specs: [],
  },
  {
    id: "pvc-tr-8",
    name: "PVC Door 8",
    tag: "Turkish",
    variants: [{ image: "https://lh3.googleusercontent.com/d/1RUvhvfKAsnaVObdjq8VihZMxe6YiG6Nz", color: "" }],
    description: "",
    specs: [],
  },
  {
    id: "pvc-tr-9",
    name: "PVC Door 9",
    tag: "Turkish",
    variants: [{ image: "https://lh3.googleusercontent.com/d/1Uy8OoFLW8OcypPL5a5TuI7j15rsf8ziF", color: "" }],
    description: "",
    specs: [],
  },
  {
    id: "pvc-tr-10",
    name: "PVC Door 10",
    tag: "Turkish",
    variants: [{ image: "https://lh3.googleusercontent.com/d/1VWvZlE1gybUvcZN6vfP-d5b_oOT_2wQA", color: "" }],
    description: "",
    specs: [],
  },
  {
    id: "pvc-tr-11",
    name: "PVC Door 11",
    tag: "Turkish",
    variants: [{ image: "https://lh3.googleusercontent.com/d/1XBEHDtgHn03hyODt3ZRwzg8--ttbobrW", color: "" }],
    description: "",
    specs: [],
  },
  {
    id: "pvc-tr-12",
    name: "PVC Door 12",
    tag: "Turkish",
    variants: [{ image: "https://lh3.googleusercontent.com/d/1XKFQUlrP1u7So6e8hu5Xc_hRuKfXrNMa", color: "" }],
    description: "",
    specs: [],
  },
  {
    id: "pvc-tr-13",
    name: "PVC Door 13",
    tag: "Turkish",
    variants: [{ image: "https://lh3.googleusercontent.com/d/1Xf_-QD-omvR9XytaNw3S2drNPaAGTn5j", color: "" }],
    description: "",
    specs: [],
  },
  {
    id: "pvc-tr-14",
    name: "PVC Door 14",
    tag: "Turkish",
    variants: [{ image: "https://lh3.googleusercontent.com/d/1Ye8-gKw7l78yshj_HcbH8R5oUXAS043Y", color: "" }],
    description: "",
    specs: [],
  },
  {
    id: "pvc-tr-15",
    name: "PVC Door 15",
    tag: "Turkish",
    variants: [{ image: "https://lh3.googleusercontent.com/d/1YeKE27k25MWOBhxsTuE-1YeiSf2poc4F", color: "" }],
    description: "",
    specs: [],
  },
  {
    id: "pvc-tr-16",
    name: "PVC Door 16",
    tag: "Turkish",
    variants: [{ image: "https://lh3.googleusercontent.com/d/1YewIuwEVDuyY6dgP11hhkoLoVh6VEJ5A", color: "" }],
    description: "",
    specs: [],
  },
  {
    id: "pvc-tr-17",
    name: "PVC Door 17",
    tag: "Turkish",
    variants: [{ image: "https://lh3.googleusercontent.com/d/1_SaPkMw-EVxU5Du_i_5MR9MIJ2Ap1WID", color: "" }],
    description: "",
    specs: [],
  },
  {
    id: "pvc-tr-18",
    name: "PVC Door 18",
    tag: "Turkish",
    variants: [{ image: "https://lh3.googleusercontent.com/d/1eoBo6oaZvqX18AeD7gPp6r3zsM2_nUih", color: "" }],
    description: "",
    specs: [],
  },
  {
    id: "pvc-tr-19",
    name: "PVC Door 19",
    tag: "Turkish",
    variants: [{ image: "https://lh3.googleusercontent.com/d/1iDvGJQoQJIhbXfCb5TOZ7NpbZYZDOth0", color: "" }],
    description: "",
    specs: [],
  },
  {
    id: "pvc-tr-20",
    name: "PVC Door 20",
    tag: "Turkish",
    variants: [{ image: "https://lh3.googleusercontent.com/d/1lR8OamDFrZzcl0Jy3sG7bJ1Fu--zmOtR", color: "" }],
    description: "",
    specs: [],
  },
  {
    id: "pvc-tr-21",
    name: "PVC Door 21",
    tag: "Turkish",
    variants: [{ image: "https://lh3.googleusercontent.com/d/1mvM8E8RnaK9hXjZvsK7KUzkAdUzJRIwY", color: "" }],
    description: "",
    specs: [],
  },
  {
    id: "pvc-tr-22",
    name: "PVC Door 22",
    tag: "Turkish",
    variants: [{ image: "https://lh3.googleusercontent.com/d/1nD6BMgAAfqGjvJZY9MRLeELOgQNGaccw", color: "" }],
    description: "",
    specs: [],
  },
  {
    id: "pvc-tr-23",
    name: "PVC Door 23",
    tag: "Turkish",
    variants: [{ image: "https://lh3.googleusercontent.com/d/1oBZW_hHf-Zl8Jwpo5qn3UKHQUKctF3me", color: "" }],
    description: "",
    specs: [],
  },
  {
    id: "pvc-tr-24",
    name: "PVC Door 24",
    tag: "Turkish",
    variants: [{ image: "https://lh3.googleusercontent.com/d/1oyXqosXFfDIxuXhJPptJwIB0iaNYDFgE", color: "" }],
    description: "",
    specs: [],
  },
  {
    id: "pvc-tr-25",
    name: "PVC Door 25",
    tag: "Turkish",
    variants: [{ image: "https://lh3.googleusercontent.com/d/1pC2X_hz2yJjvlgM08hOUG85VcDUiS0HA", color: "" }],
    description: "",
    specs: [],
  },
  {
    id: "pvc-tr-26",
    name: "PVC Door 26",
    tag: "Turkish",
    variants: [{ image: "https://lh3.googleusercontent.com/d/1qiDt-9YtiJu6pPXUr79W62EaR_KHQZJq", color: "" }],
    description: "",
    specs: [],
  },
  {
    id: "pvc-tr-27",
    name: "PVC Door 27",
    tag: "Turkish",
    variants: [{ image: "https://lh3.googleusercontent.com/d/1qpAa8hd8cVWY2IDE61I881NWz8fkG4Nh", color: "" }],
    description: "",
    specs: [],
  },
  {
    id: "pvc-tr-28",
    name: "PVC Door 28",
    tag: "Turkish",
    variants: [{ image: "https://lh3.googleusercontent.com/d/1tqKVMUszyy3SNgeQ-sk42MI5tM4A2DxB", color: "" }],
    description: "",
    specs: [],
  },
  {
    id: "pvc-tr-29",
    name: "PVC Door 29",
    tag: "Turkish",
    variants: [{ image: "https://lh3.googleusercontent.com/d/1vESr-SebpsHQYa3FFFst9ICcItq8o6hE", color: "" }],
    description: "",
    specs: [],
  },
  {
    id: "pvc-tr-30",
    name: "PVC Door 30",
    tag: "Turkish",
    variants: [{ image: "https://lh3.googleusercontent.com/d/1xq40G-ELK9geGhmvW7m7Up20oOkikBoV", color: "" }],
    description: "",
    specs: [],
  },

  // ── Chinese Made ─────────────────────────────────────────────────────────────
  {
    id: "pvc-cn-1",
    name: "PVC Door 31",
    tag: "Chinese",
    variants: [{ image: "https://lh3.googleusercontent.com/d/1-KYhLT7vnVvnzn9SGrl4XwOpj_qaR2Xu", color: "" }],
    description: "",
    specs: [],
  },
  {
    id: "pvc-cn-2",
    name: "PVC Door 32",
    tag: "Chinese",
    variants: [{ image: "https://lh3.googleusercontent.com/d/1-YQGkqR5P3aWGGGhcCkNiY5dOD72oUl1", color: "" }],
    description: "",
    specs: [],
  },
  {
    id: "pvc-cn-3",
    name: "PVC Door 33",
    tag: "Chinese",
    variants: [{ image: "https://lh3.googleusercontent.com/d/16iUL7neKgXYHgJ-dNc0NBcE9-z3L6c1q", color: "" }],
    description: "",
    specs: [],
  },
  {
    id: "pvc-cn-4",
    name: "PVC Door 34",
    tag: "Chinese",
    variants: [{ image: "https://lh3.googleusercontent.com/d/1DU9eUG7haYMaH5F5l9a3qQcbc_QNGZp6", color: "" }],
    description: "",
    specs: [],
  },
  {
    id: "pvc-cn-5",
    name: "PVC Door 35",
    tag: "Chinese",
    variants: [{ image: "https://lh3.googleusercontent.com/d/1KxmY3lbLBpRZTezoJmCbGfmA8IM5hzfq", color: "" }],
    description: "",
    specs: [],
  },
  {
    id: "pvc-cn-6",
    name: "PVC Door 36",
    tag: "Chinese",
    variants: [{ image: "https://lh3.googleusercontent.com/d/1MXFIYlw5LRQvFaHbuqDvfo2MynGDyOVD", color: "" }],
    description: "",
    specs: [],
  },
  {
    id: "pvc-cn-7",
    name: "PVC Door 37",
    tag: "Chinese",
    variants: [{ image: "https://lh3.googleusercontent.com/d/1PSLoizK1ATsRxKb3j7IGQNBPBvvTZxpl", color: "" }],
    description: "",
    specs: [],
  },
  {
    id: "pvc-cn-8",
    name: "PVC Door 38",
    tag: "Chinese",
    variants: [{ image: "https://lh3.googleusercontent.com/d/1SILKpJyUEBlv7AEExOZ7dOJy_-b5PS52", color: "" }],
    description: "",
    specs: [],
  },
  {
    id: "pvc-cn-9",
    name: "PVC Door 39",
    tag: "Chinese",
    variants: [{ image: "https://lh3.googleusercontent.com/d/1VYIPsHPUeVpgJETuvsLokNM5rMQXdUEU", color: "" }],
    description: "",
    specs: [],
  },
  {
    id: "pvc-cn-10",
    name: "PVC Door 40",
    tag: "Chinese",
    variants: [{ image: "https://lh3.googleusercontent.com/d/1ZEI8LiMyAYWTnTtKqJog4VW19VXNs8-R", color: "" }],
    description: "",
    specs: [],
  },
  {
    id: "pvc-cn-11",
    name: "PVC Door 41",
    tag: "Chinese",
    variants: [{ image: "https://lh3.googleusercontent.com/d/1a_BSmjMeX0BKIFNtHipE8zrQACffUKq_", color: "" }],
    description: "",
    specs: [],
  },
  {
    id: "pvc-cn-12",
    name: "PVC Door 42",
    tag: "Chinese",
    variants: [{ image: "https://lh3.googleusercontent.com/d/1dTLu35f2tEsKUIqZrZV0uM9tlYdjxV0n", color: "" }],
    description: "",
    specs: [],
  },
  {
    id: "pvc-cn-13",
    name: "PVC Door 43",
    tag: "Chinese",
    variants: [{ image: "https://lh3.googleusercontent.com/d/1mimdxZZpj2Q_k2ji7t7-LuLFYe9gTqOX", color: "" }],
    description: "",
    specs: [],
  },
  {
    id: "pvc-cn-14",
    name: "PVC Door 44",
    tag: "Chinese",
    variants: [{ image: "https://lh3.googleusercontent.com/d/1oLwQ6NMK_lnclQROuVdHjON9nKUCAbdC", color: "" }],
    description: "",
    specs: [],
  },
  {
    id: "pvc-cn-15",
    name: "PVC Door 45",
    tag: "Chinese",
    variants: [{ image: "https://lh3.googleusercontent.com/d/1siFwO97N_Llf9c40JCMxftoRGKJUEPkP", color: "" }],
    description: "",
    specs: [],
  },
  {
    id: "pvc-cn-16",
    name: "PVC Door 46",
    tag: "Chinese",
    variants: [{ image: "https://lh3.googleusercontent.com/d/1tZP6Cwqt7D3Ifbjmp-aKE7_AV1bDvkd5", color: "" }],
    description: "",
    specs: [],
  },
  {
    id: "pvc-cn-17",
    name: "PVC Door 47",
    tag: "Chinese",
    variants: [{ image: "https://lh3.googleusercontent.com/d/1tiERj-32bvwKGKB6eAV-MPWYUMZkAESy", color: "" }],
    description: "",
    specs: [],
  },
  {
    id: "pvc-cn-18",
    name: "PVC Door 48",
    tag: "Chinese",
    variants: [{ image: "https://lh3.googleusercontent.com/d/1ySOznCRaEKflLJytzC1LKXj16AdcOBix", color: "" }],
    description: "",
    specs: [],
  },
];

export function PvcDoorsPage() {
  const { t } = useTranslation();
  return (
    <DoorPageShell
      icon={Droplets}
      title={t('doors.pvc_title')}
      subtitle={t('doors.pvc_page_sub')}
      description={t('doors.pvc_page_desc')}
      doorType="PVC Doors"
    >
      <DoorGrid
        products={products}
        filters={["Turkish", "Chinese"]}
        filterKey={(p) => p.tag ?? ""}
        doorType="PVC Doors"
      />
    </DoorPageShell>
  );
}
